// internal/employee/repository_impl.go
package employee

import (
	"context"
	"fmt"
	"sync"
)

// inMemoryEmployeeRepository adalah implementasi in-memory dari EmployeeRepository
type inMemoryEmployeeRepository struct {
	mu     sync.RWMutex
	data   map[string]Employee
	nextID int
}

// NewInMemoryEmployeeRepository membuat instance baru dari repository in-memory
func NewInMemoryEmployeeRepository() EmployeeRepository {
	return &inMemoryEmployeeRepository{
		data:   make(map[string]Employee),
		nextID: 1,
	}
}

func (r *inMemoryEmployeeRepository) FindAll(ctx context.Context) ([]Employee, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	employees := make([]Employee, 0, len(r.data))
	for _, emp := range r.data {
		employees = append(employees, emp)
	}
	return employees, nil
}

func (r *inMemoryEmployeeRepository) FindByID(ctx context.Context, id string) (Employee, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	emp, exists := r.data[id]
	if !exists {
		return Employee{}, fmt.Errorf("employee with id %s not found", id)
	}
	return emp, nil
}

func (r *inMemoryEmployeeRepository) Save(ctx context.Context, emp Employee) (Employee, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	id := fmt.Sprintf("EMP-%03d", r.nextID)
	r.nextID++
	emp.ID = id // Assign ID generated by repository
	r.data[id] = emp
	return emp, nil
}

func (r *inMemoryEmployeeRepository) Update(ctx context.Context, id string, emp Employee) (Employee, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	_, exists := r.data[id]
	if !exists {
		return Employee{}, fmt.Errorf("employee with id %s not found", id)
	}

	emp.ID = id // Ensure ID remains the same
	r.data[id] = emp
	return emp, nil
}

func (r *inMemoryEmployeeRepository) Delete(ctx context.Context, id string) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	_, exists := r.data[id]
	if !exists {
		return fmt.Errorf("employee with id %s not found", id)
	}

	delete(r.data, id)
	return nil
}
